# Use an official PostgreSQL image as a parent image
FROM postgres:latest

# Expose the PostgreSQL port
EXPOSE 5432

# Environment variables
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=mydatabase
